n0q/hackmaster5e-fvtt

- modules/actor/actor-sheet.js
- modules/actor/actor.js
- modules/sys/partials.js
- template.json
- templates/actor/actor-base.hbs
- templates/actor/parts/header/header-portrait.hbs
- templates/actor/parts/setup/base-setup.hbs
- templates/item/item-character_class-sheet.hbs
- templates/item/item-class-sheet.hbs
Character classes exist. They display on the character sheet and can be configured in a 'setup' tab. Presently, they provide top bonuses and hp. hp reroll is observed, but it doesn't handle multiple rerolls in a row, yet. Presently does nothing else, but it is a start.
> character class functionality

- lang/en.json
- modules/actor/actor-sheet.js
- modules/actor/actor.js
- modules/item/item-sheet.js
- modules/sys/partials.js
- scss/helpers/_mixins.scss
- scss/layout/_actor-sheet.scss
- styles/hackmaster.css
- template.json
- templates/actor/actor-base.hbs
- templates/actor/parts/abilities.hbs
- templates/actor/parts/setup/base-setup.hbs
- templates/actor/parts/setup/setup-abilities.hbs
- templates/actor/parts/setup/setup-classes.hbs
- templates/item/item-race-sheet.hbs
racial bonuses are kept separate from raw ability score, now. beginning of a setup section for controlling modifiers.
> beginning of stat modifiers

- modules/actor/actor.js
- template.json
- templates/actor/parts/setup/setup-abilities.hbs
> misc and (ro) racial mods in setup pane

- modules/actor/actor.js
- modules/sys/partials.js
- scss/hackmaster.scss
- scss/layout/_actor-sheet.scss
- scss/parts/_cards.scss
- scss/parts/_items.scss
- styles/hackmaster.css
- system.json
- template.json
- templates/actor/actor-base.hbs
- templates/actor/parts/combat/base-combat.hbs
- templates/actor/parts/combat/combat-armor.hbs
- templates/actor/parts/combat/combat-weapons.hbs
- templates/actor/parts/setup/setup-abilities.hbs
- templates/actor/parts/setup/setup-profs.hbs
- templates/item/item-weapon-sheet.hbs
This is honestly more of a catchup-pull, since I've been lazy about pulling to dev.
> data structure refactor, beginning of weapon cards

- modules/actor/actor-sheet.js
- modules/actor/actor.js
- scss/helpers/_mixins.scss
- scss/helpers/_variables.scss
- scss/parts/_cards.scss
- styles/hackmaster.css
- templates/actor/parts/abilities.hbs
- templates/actor/parts/combat/combat-weapons.hbs
- templates/item/item-weapon-sheet.hbs
wounds now behave as one would expect. When duration reaches zero, hp drops by 1 and duration = hp.
> wound degradation logic

- modules/actor/actor-sheet.js
- modules/actor/actor.js
- scss/parts/_cards.scss
- styles/hackmaster.css
- system.json
- templates/actor/parts/combat/combat-weapons.hbs
can manipulate editable data on weapon cards. some css will be needed to make it clear what can be edited and what can not, but this will suffice for now.
> editable weapon cards

- modules/hackmaster.js
- modules/sys/combat.js
Combat gets sorted in reverse order, and I've hackishly done away with that inferior "combat turns" as found in other, lesser game systems.
Still needs option to pick a die, and an easy way to change your init.
> first pass on combat tracker

- modules/actor/actor-sheet.js
- modules/chat/chat.js
- system.json
- templates/actor/parts/combat/cards/weapon.hbs
- templates/actor/parts/skills.hbs
still more to do here, but a good start. We could have custom roll cards at this point.
> _onroll refactor

- lang/en.json
- modules/actor/actor-sheet.js
- modules/chat/chat.js
- modules/sys/localize.js
- scss/cards/_saves.scss
- scss/hackmaster.scss
- scss/layout/_actor-sheet.scss
- scss/parts/_cards.scss
- styles/hackmaster.css
- templates/actor/parts/middle/cards/saves.hbs
- templates/actor/parts/middle/middle-saves.hbs
Working saves, and with a visual I can live with for now.
> functioning and visually acceptable saves

- modules/hackmaster.js
Now handles non-die terms, including PoolTerms.
> dsn crash fixed for real this time.

- modules/actor/actor-sheet.js
- modules/chat/chat.js
- modules/hackmaster.js
Basic combat roll interpretation. Die results are not modified (yet), but the system will inform you if you've rolled a crit, perfect, near-perfect, or superior attack/defense.
> combat roll interpretor

- modules/actor/actor-sheet.js
- modules/chat/chat.js
- scss/parts/_cards.scss
- styles/hackmaster.css
- system.json
- templates/actor/parts/combat/cards/weapon.hbs
cards no longer rely on item flags to determine their state. generalized jquery toggle class for determining ui element status.
> user independent card state toggles

- lang/en.json
- modules/sys/localize.js
- scss/cards/_inventory.scss
- styles/hackmaster.css
- templates/actor/parts/inventory/cards/item.hbs
inventory css is fine. There's a lot of room for additional data, making item cards look sparse, but that's okay. I'll provide more item-specific data later on, especially during the inventory arc.
> functional inventory

- README.md
- modules/actor/actor-sheet.js
- modules/actor/actor.js
- templates/actor/parts/skills.hbs
universal skills now autopopulate with correct untrained mastery values.
> uskill default values honored

- .github/workflows/release.yml
- modules/sys/helpers.js
- package-lock.json
- package.json
- system.json
added DOMPurify for sanitation purposes.
> sanitizer support

- modules/actor/actor.js
- modules/sys/localize.js
- template.json
- templates/actor/cards/armor.hbs
- templates/actor/cards/weapon.hbs
- templates/actor/parts/combat/combat-armors.hbs
- templates/actor/parts/combat/combat-weapons.hbs
- templates/item/item-armor-sheet.hbs
Gave armor cards the same treatment as weapon cards. Weapons no longer use armors which are not equipped.
> armor cards and equipped status

- lang/en.json
- modules/mgr/chatmgr.js
- modules/mgr/dialogmgr.js
- modules/sys/constants.js
- modules/sys/localize.js
- template.json
- templates/actor/cards/armor.hbs
- templates/actor/cards/weapon.hbs
- templates/dialog/getRangedAttack.hbs
- templates/item/item-weapon-sheet.hbs
Weapon cards differ slightly for ranged weapons, now. Ranged attack dialog requests weapon range from the user and both applies this penalty to the roll and the chat card.
> initial ranged support

- lang/en.json
- template.json
- templates/actor/parts/header/header-portrait.hbs
- templates/item/item-race-sheet.hbs
Added racial adjectives for display purposes. Now you can have a 'Gnome' race which allows for a 'Gnomish Mage'.
> racial adjectives

- hm.js
- modules/actor/actor.js
- modules/item/item.js
- template.json
Minor trimming to the data collection nightmare that lives in actor.js. Along the way I'm fixing some new bugs and cutting some base data off the template.json. This closes #153
> minor data collection refactor

- modules/actor/actor.js
- modules/item/item.js
- modules/sys/partials.js
- templates/actor/parts/biography.hbs
- templates/item/item-armor-sheet.hbs
- templates/item/item-cclass-sheet.hbs
- templates/item/item-item-sheet.hbs
- templates/item/item-race-sheet.hbs
- templates/item/item-skill-sheet.hbs
- templates/item/item-spell-sheet.hbs
- templates/item/item-weapon-sheet.hbs
- templates/item/item-wound-sheet.hbs
- templates/item/parts/description.hbs
> minor sheet fixes

- templates/chat/spell.hbs
> update spell card template to use domains

- modules/actor/beast-actor-sheet.js
- modules/item/item-sheet.js
- modules/item/item.js
- modules/sys/constants.js
- template.json
- templates/item/item-armor-sheet.hbs
- templates/item/item-weapon-sheet.hbs
weapons and armors have a 'qn' member which serves as a scalar against the effects of quality on armor and melee/ranged weapons. The resulting vector is added to totals as per normal.
> added weapon/armor quality
